metrics:
- alert_names:
  - Kafka_Broker_BytesIn_PerSec_Warning
  - Kafka_Broker_BytesIn_PerSec_Critical
  best_model:
    f1_score: 0.8928571428571429
    name: RandomForest
  description: Rate of bytes ingested by the Kafka broker per second.
  name: kafka_broker_bytes_in_per_sec
  query: rate(kafka_server_brokertopicmetrics_bytesinpersec[5m])
  step: 15s
  thresholds:
    critical: 3000000
    warning: 1500000
  time_range: 6h
prometheus_url: http://localhost:9090
